F.vim.nmap('<C-n>',       ':BufferLineCycleNext<CR>')
F.vim.nmap('<C-p>',       ':BufferLineCyclePrev<CR>')
F.vim.nmap('<C-S-b>',     ':BufferLinePick<CR>')
F.vim.nmap('<C-=>',       ':BufferLineMoveNext<CR>')
F.vim.nmap('<C-->',       ':BufferLineMovePrev<CR>')
F.vim.nmap('<Leader>bch', ':BufferLineCloseLeft<CR>')
F.vim.nmap('<Leader>bcl', ':BufferLineCloseRight<CR>')
F.vim.nmap('<Leader>bp',  ':BufferLineTogglePin<CR>')
F.vim.nmap('<Leader>bg',  ':BufferLinePick<CR>')

F.vim.nmap('<C-1>', '<Cmd>BufferLineGoToBuffer 1<CR>')
F.vim.nmap('<C-2>', '<Cmd>BufferLineGoToBuffer 2<CR>')
F.vim.nmap('<C-3>', '<Cmd>BufferLineGoToBuffer 3<CR>')
F.vim.nmap('<C-4>', '<Cmd>BufferLineGoToBuffer 4<CR>')
F.vim.nmap('<C-5>', '<Cmd>BufferLineGoToBuffer 5<CR>')
F.vim.nmap('<C-6>', '<Cmd>BufferLineGoToBuffer 6<CR>')
F.vim.nmap('<C-7>', '<Cmd>BufferLineGoToBuffer 7<CR>')
F.vim.nmap('<C-8>', '<Cmd>BufferLineGoToBuffer 8<CR>')
F.vim.nmap('<C-$>', '<Cmd>BufferLineGoToBuffer -1<CR>')
