vnoremap b= :<C-u>normal! ^vt=<CR>
onoremap b= :<C-u>normal! ^vt=<CR>
vnoremap b: :<C-u>normal! ^vt:<CR>
onoremap b: :<C-u>normal! ^vt:<CR>
vnoremap b- :<C-u>normal! ^vt-<CR>
onoremap b- :<C-u>normal! ^vt-<CR>
vnoremap B= :<C-u>normal! ^vf=<CR>
onoremap B= :<C-u>normal! ^vf=<CR>
vnoremap B: :<C-u>normal! ^vf:<CR>
onoremap B: :<C-u>normal! ^vf:<CR>
vnoremap B- :<C-u>normal! ^vf-<CR>
onoremap B- :<C-u>normal! ^vf-<CR>
