git clone https://github.com/emacs-evil/evil/                      ~/.emacs.d/packages/evil
git clone https://github.com/gabesoft/evil-mc/                     ~/.emacs.d/packages/evil-mc
git clone https://github.com/cofi/evil-leader/                     ~/.emacs.d/packages/evil-leader
git clone https://github.com/emacs-evil/evil-surround/             ~/.emacs.d/packages/evil-surround
git clone https://github.com/redguardtoo/evil-nerd-commenter/      ~/.emacs.d/packages/evil-nerd-commenter
git clone https://github.com/TheBB/evil-indent-plus/               ~/.emacs.d/packages/evil-indent-plus
git clone https://github.com/syl20bnr/evil-escape/                 ~/.emacs.d/packages/evil-escape
git clone https://github.com/cofi/evil-numbers/                    ~/.emacs.d/packages/evil-numbers
git clone https://github.com/noctuid/evil-textobj-column/          ~/.emacs.d/packages/evil-textobj-column
git clone https://github.com/supermomonga/evil-textobj-entire/     ~/.emacs.d/packages/evil-textobj-entire
git clone https://github.com/syohex/evil-textobj-line/             ~/.emacs.d/packages/evil-textobj-line
git clone https://github.com/noctuid/evil-textobj-anyblock/        ~/.emacs.d/packages/evil-textobj-anyblock
git clone https://github.com/redguardtoo/evil-matchit/             ~/.emacs.d/packages/evil-matchit
git clone https://github.com/edkolev/evil-lion/                    ~/.emacs.d/packages/evil-lion
git clone https://github.com/wcsmith/evil-args/                    ~/.emacs.d/packages/evil-args
git clone https://github.com/7696122/evil-terminal-cursor-changer/ ~/.emacs.d/packages/evil-terminal-cursor-changer
git clone https://github.com/alexmurray/evil-vimish-fold/          ~/.emacs.d/packages/evil-vimish-fold
git clone https://github.com/mrkkrp/vimish-fold/                   ~/.emacs.d/packages/vimish-fold
git clone https://github.com/noctuid/targets.el/                   ~/.emacs.d/packages/targets.el
git clone https://github.com/winterTTr/ace-jump-mode/              ~/.emacs.d/packages/ace-jump-mode
git clone https://github.com/milkypostman/powerline/               ~/.emacs.d/packages/powerline
git clone https://github.com/jonathanchu/emacs-powerline/          ~/.emacs.d/packages/emacs-powerline
git clone https://github.com/AnthonyDiGirolamo/airline-themes/     ~/.emacs.d/packages/airline-themes
git clone https://github.com/gabesoft/evil-mc/                     ~/.emacs.d/packages/evil-mc
git clone https://github.com/Somelauw/evil-org-mode/               ~/.emacs.d/packages/evil-org-mode
git clone https://github.com/krisajenkins/evil-tabs/               ~/.emacs.d/packages/evil-tabs
git clone https://github.com/edkolev/evil-goggles/                 ~/.emacs.d/packages/evil-goggles
git clone https://github.com/tarao/evil-plugins/               	   ~/.emacs.d/packages/evil-plugins
git clone https://github.com/dracula/emacs/                        ~/.emacs.d/themes
