[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "alacritty"

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[scrolling]
history = 10000

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 14
y = 10

[general]
live_config_reload = true
import = ["~/.config/alacritty/keys.toml"]
