let g:tokyonight_style = 'night' "night|storm
let g:tokyonight_enable_italic = 1
let g:tokyonight_disable_italic_comment = 0
let g:tokyonight_transparent_background = 1
let g:tokyonight_menu_selection_background = 'green' "green|red|blue
let g:tokyonight_cursor = 'auto' "auto|red|green|blue
let g:tokyonight_current_word = 'grey background' "bold|underline|itatlic|grey background
"let g:airline_theme = "tokyonight"
"let g:lightline = {'colorscheme' : 'tokyonight'}
