F.nvim.vmap('gkbll', '<cmd>CBlbox<cr>')
F.nvim.vmap('gkbcl', '<cmd>CBclbox<cr>')
F.nvim.vmap('gkblc', '<cmd>CBcbox<cr>')
F.nvim.vmap('gkbcc', '<cmd>CBccbox<cr>')
F.nvim.vmap('gkbLl', '<cmd>CBalbox<cr>')
F.nvim.vmap('gkbCl', '<cmd>CBaclbox<cr>')
F.nvim.vmap('gkbLc', '<cmd>CBacbox<cr>')
F.nvim.vmap('gkbCc', '<cmd>CBaccbox<cr>')

F.nvim.nmap('gkll', '<cmd>CBline<cr>')
F.nvim.nmap('gklc', '<cmd>CBcline<cr>')
