vim.cmd [[ nnoremap <silent> <Leader>pr <cmd>Mru<CR> ]]
vim.cmd [[ nnoremap <silent> <Leader>pR <cmd>Mfu<CR> ]]
vim.cmd [[ nnoremap <silent> <Leader>pa <cmd>MruAdd<CR> ]]
vim.cmd [[ nnoremap <silent> <Leader>pd <cmd>MfuDel<CR> ]]
vim.cmd [[ nnoremap <silent> <Leader>pO <cmd>MruRepos<CR> ]]
