-- float|split
-- operations
	-- search
	-- replace
	-- operation(singleline/multiline)
	-- quickfix
-- filters
	-- include|exclude
		-- filename = extension/glob/regex
		-- contents (vim-style)
		-- buffers
			-- filetype
			-- content
			-- filename filters
-- preview
	-- edit
	-- context
-- icons
